### ISSUE TITLE
ESPN Player not working anymore ? 

### ISSUE THREAD

**Issue by Displayel** [emilsvennesson/kodi-espnplayer#6]
Just downloaded the latest version, when i log in i see 3 Folders "NCAA" , "Indy Car" and "ESPN Select" i can´t enter any of them, Kodi 17.4 on a Nvidia Shield

**Comment by Ruanjoma** [comment]
Same here Openelec Kodi 17.3

**Comment by redmanhsl** [comment]
Doesn't work for me either. I can't even access the app. Won't load.

**Comment by mickeelm** [comment]
Same here, however I just tried @mdklein's fork (branch fixed2017) and I was able to watch a live stream. I don't know what the differences are really as I haven't dug into the code anything but my very brief test was successful.

**Comment by mickeelm** [comment]
@emilsvennesson just a friendly question here :) Are you interested in doing more development on this plugin or is it likely that you will not update it further? I'm a Java dev but use Python sometimes on smaller hobby stuff. I do have a valid ESPN subscription as well (and will renew it again soon). So - if you think that you have an idea about what's going on/needs to be fixed then maybe I could dig into it. Like I wrote in my last comment, at least for my purposes @mdklein's fork worked fine. But I guess it would be nice to have a working "official" repo as well.

**Comment by emilsvennesson** [comment]
@mickeelm Hi! 😀

I'm no longer subscribed and don't have the motivation to work on something I'm not using myself right now.

I'd happily let you and/or @mdklein take over and submit a working version to the official repo. I was in the middle of a rewrite when I abandoned this (whoops) so I'm unsure about the current state of the code.

**Comment by mdklein** [comment]
@emilsvennesson 

I'm still subscribing, and would be able to continue the work.

**Comment by mickeelm** [comment]
That's great! The plugin is too great to die :) @mdklein is there anything I can do to help/you'd like me to take a look at? Like I mentioned before Python isn't my main programming language (I am a professional Java dev, though) but I'd be happy to help in any way I can.

**Comment by mdklein** [comment]
@emilsvennesson, anything I need to do to take over the official repo? Probably should try to get a working version up before the college kickoff... 

That said, I haven't actually checked my 2017fix version lately... hope they didn't make too many changes.

**Comment by emilsvennesson** [comment]
@mdklein I just sent you a collaborator invite. :)

**Comment by mdklein** [comment]
Awesome, I just accepted it... I'll take a look at it this weekend, and hopefully get things working.

**Comment by mdklein** [comment]
Fixes should be on official kodi repo now. Check your updates, let me know if you hit any bugs.

**Comment by mickeelm** [comment]
Running it right now, working like a charm so far. **EXCELLENT!** Thank you for taking this on.

This issue should be closed I think, and then possibly file bug reports as separate issues.
